version: "3.1"
services:
  manabie-postgres:
    image: postgres:13.0
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - network-manabie

  manabie-service:
    privileged: true
    image: $IMAGE:$VERSION
    container_name: $CONTAINER
    depends_on:
      - manabie-postgres
    restart: always
    environment:
      server_port: $PORT
      pg_host: manabie-postgres
      pg_port: 5432    
      pg_user: $POSTGRES_USER
      pg_password: $POSTGRES_PASSWORD
      pg_db_name: $POSTGRES_DB
    build:
      context: .
      dockerfile: Dockerfile    
    command: ./server
    ports:
      - '${PORT}:${PORT}'
    expose:
      - ${PORT}
    networks:
      - network-manabie

networks:
  network-manabie: